#!/usr/bin/env node
/**
 * Sync the worker-embedded observatory asset from the canonical dossier HTML.
 *
 * Source of truth: ../observatory/dossier/index.html
 * Generated:      ./src/observatory-asset.ts
 *
 * The Spacebase1 Worker can't load files at runtime, so we ship the dashboard
 * as a string literal embedded in src/observatory-asset.ts. To avoid two-copy
 * drift between the standalone dossier (which we vendor into the agent-pack)
 * and the embedded asset, we keep the HTML file authoritative and regenerate
 * the TS module from it.
 *
 * Usage:
 *   cd spacebase1 && npm run generate:observatory
 *
 * In CI you can call this with `--check` to fail when the embedded asset has
 * drifted from the canonical HTML:
 *
 *   npm run generate:observatory -- --check
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..');
const sourcePath = resolve(repoRoot, 'observatory', 'dossier', 'index.html');
const targetPath = resolve(repoRoot, 'spacebase1', 'src', 'observatory-asset.ts');

const checkOnly = process.argv.includes('--check');

const html = readFileSync(sourcePath, 'utf8');

const lines = html.split('\n');
const literalLines = lines.map((line, idx) => {
  const escaped = line.replaceAll('\\', '\\\\').replaceAll("'", "\\'");
  const isLast = idx === lines.length - 1;
  return `  '${escaped}${isLast ? '' : '\\n'}'`;
});

const generated = `// AUTOGENERATED by spacebase1/scripts/generate-observatory-asset.ts
// Source of truth: observatory/dossier/index.html
// Run \`npm run generate:observatory\` after editing the dossier HTML.
//
// Do not edit this file by hand.

export const OBSERVATORY_HTML =
${literalLines.join(' +\n')};
`;

if (checkOnly) {
  const current = readFileSync(targetPath, 'utf8');
  if (current !== generated) {
    console.error(`✘ ${targetPath} is out of sync with ${sourcePath}.`);
    console.error('  Run: npm run generate:observatory');
    process.exit(1);
  }
  console.log('✓ observatory-asset.ts is in sync with dossier/index.html');
  process.exit(0);
}

writeFileSync(targetPath, generated);
console.log(`✓ Wrote ${targetPath} (${generated.length} bytes from ${html.length} bytes of HTML)`);
