import { execFileSync } from 'child_process';
import { resolve } from 'path';
import { fileURLToPath } from 'url';
import { describe, expect, it } from 'vitest';

const here = resolve(fileURLToPath(import.meta.url), '..');
const generator = resolve(here, 'generate-observatory-asset.ts');

describe('observatory-asset.ts drift guard', () => {
  // The worker-embedded asset is autogenerated from observatory/dossier/index.html.
  // If they drift, someone edited the generated file by hand instead of the
  // canonical HTML, and the next regen will silently overwrite their work.
  // Catch that here, in the same test run that everything else runs in.
  it('matches observatory/dossier/index.html (regenerate with `npm run generate:observatory`)', () => {
    let stderr = '';
    let exitCode = 0;
    try {
      execFileSync('node', ['--experimental-strip-types', generator, '--check'], {
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'pipe'],
      });
    } catch (err) {
      const e = err as NodeJS.ErrnoException & { status?: number; stderr?: string };
      exitCode = e.status ?? 1;
      stderr = e.stderr ?? '';
    }
    expect(exitCode, `generate-observatory-asset --check failed:\n${stderr}`).toBe(0);
  });
});
